# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

IMAGE_MATH_METADATA = Metadata(
    id="fadbb78c295789002a291f08bcdf90f7f7e37437.boutiques",
    name="ImageMath",
    package="ants",
    container_image_tag="antsx/ants:v2.5.3",
)


ImageMathParameters = typing.TypedDict('ImageMathParameters', {
    "@type": typing.NotRequired[typing.Literal["ants/ImageMath"]],
    "image_dimension": typing.Literal[2, 3, 4],
    "output_image": str,
    "operations_and_inputs": str,
    "image1": InputPathType,
    "image2": typing.NotRequired[InputPathType | None],
})
ImageMathParametersTagged = typing.TypedDict('ImageMathParametersTagged', {
    "@type": typing.Literal["ants/ImageMath"],
    "image_dimension": typing.Literal[2, 3, 4],
    "output_image": str,
    "operations_and_inputs": str,
    "image1": InputPathType,
    "image2": typing.NotRequired[InputPathType | None],
})


class ImageMathOutputs(typing.NamedTuple):
    """
    Output object returned when calling `ImageMathParameters(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    output_image: OutputPathType
    """The resulting image after processing."""


def image_math_params(
    image_dimension: typing.Literal[2, 3, 4],
    output_image: str,
    operations_and_inputs: str,
    image1: InputPathType,
    image2: InputPathType | None = None,
) -> ImageMathParametersTagged:
    """
    Build parameters.
    
    Args:
        image_dimension: The dimensionality of the image. Use 2 or 3 for\
            spatial images, and 4 for 4D images like time-series data.
        output_image: The output image file resulting from the operations.
        operations_and_inputs: Mathematical operations and inputs to be applied\
            on the images.
        image1: The first input image for the operation.
        image2: The second input image for the operation, if required.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "ants/ImageMath",
        "image_dimension": image_dimension,
        "output_image": output_image,
        "operations_and_inputs": operations_and_inputs,
        "image1": image1,
    }
    if image2 is not None:
        params["image2"] = image2
    return params


def image_math_cargs(
    params: ImageMathParameters,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("ImageMath")
    cargs.append(str(params.get("image_dimension", None)))
    cargs.append(params.get("output_image", None))
    cargs.append(params.get("operations_and_inputs", None))
    cargs.append(execution.input_file(params.get("image1", None)))
    if params.get("image2", None) is not None:
        cargs.append(execution.input_file(params.get("image2", None)))
    return cargs


def image_math_outputs(
    params: ImageMathParameters,
    execution: Execution,
) -> ImageMathOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = ImageMathOutputs(
        root=execution.output_file("."),
        output_image=execution.output_file(params.get("output_image", None)),
    )
    return ret


def image_math_execute(
    params: ImageMathParameters,
    runner: Runner | None = None,
) -> ImageMathOutputs:
    """
    ImageMath
    
    A versatile tool for performing various mathematical and manipulation
    operations on images.
    
    Author: ANTs Developers
    
    URL: https://github.com/ANTsX/ANTs
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `ImageMathOutputs`).
    """
    runner = runner or get_global_runner()
    execution = runner.start_execution(IMAGE_MATH_METADATA)
    params = execution.params(params)
    cargs = image_math_cargs(params, execution)
    ret = image_math_outputs(params, execution)
    execution.run(cargs)
    return ret


def image_math(
    image_dimension: typing.Literal[2, 3, 4],
    output_image: str,
    operations_and_inputs: str,
    image1: InputPathType,
    image2: InputPathType | None = None,
    runner: Runner | None = None,
) -> ImageMathOutputs:
    """
    ImageMath
    
    A versatile tool for performing various mathematical and manipulation
    operations on images.
    
    Author: ANTs Developers
    
    URL: https://github.com/ANTsX/ANTs
    
    Args:
        image_dimension: The dimensionality of the image. Use 2 or 3 for\
            spatial images, and 4 for 4D images like time-series data.
        output_image: The output image file resulting from the operations.
        operations_and_inputs: Mathematical operations and inputs to be applied\
            on the images.
        image1: The first input image for the operation.
        image2: The second input image for the operation, if required.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `ImageMathOutputs`).
    """
    params = image_math_params(
        image_dimension=image_dimension,
        output_image=output_image,
        operations_and_inputs=operations_and_inputs,
        image1=image1,
        image2=image2,
    )
    return image_math_execute(params, runner)


__all__ = [
    "IMAGE_MATH_METADATA",
    "ImageMathOutputs",
    "image_math",
    "image_math_execute",
    "image_math_params",
]
