# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

LABEL2COLOUR_METADATA = Metadata(
    id="9c64d87e6b80097d51226570fbf47cc009d84140.boutiques",
    name="label2colour",
    package="mrtrix",
    container_image_tag="mrtrix3/mrtrix3:3.0.4",
)


Label2colourConfigParameters = typing.TypedDict('Label2colourConfigParameters', {
    "@type": typing.NotRequired[typing.Literal["config"]],
    "key": str,
    "value": str,
})
Label2colourConfigParametersTagged = typing.TypedDict('Label2colourConfigParametersTagged', {
    "@type": typing.Literal["config"],
    "key": str,
    "value": str,
})


Label2colourParameters = typing.TypedDict('Label2colourParameters', {
    "@type": typing.NotRequired[typing.Literal["mrtrix/label2colour"]],
    "lut": typing.NotRequired[InputPathType | None],
    "info": bool,
    "quiet": bool,
    "debug": bool,
    "force": bool,
    "nthreads": typing.NotRequired[int | None],
    "config": typing.NotRequired[list[Label2colourConfigParameters] | None],
    "help": bool,
    "version": bool,
    "nodes_in": InputPathType,
    "colour_out": str,
})
Label2colourParametersTagged = typing.TypedDict('Label2colourParametersTagged', {
    "@type": typing.Literal["mrtrix/label2colour"],
    "lut": typing.NotRequired[InputPathType | None],
    "info": bool,
    "quiet": bool,
    "debug": bool,
    "force": bool,
    "nthreads": typing.NotRequired[int | None],
    "config": typing.NotRequired[list[Label2colourConfigParameters] | None],
    "help": bool,
    "version": bool,
    "nodes_in": InputPathType,
    "colour_out": str,
})


def label2colour_config_params(
    key: str,
    value: str,
) -> Label2colourConfigParametersTagged:
    """
    Build parameters.
    
    Args:
        key: temporarily set the value of an MRtrix config file entry.
        value: temporarily set the value of an MRtrix config file entry.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "config",
        "key": key,
        "value": value,
    }
    return params


def label2colour_config_cargs(
    params: Label2colourConfigParameters,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("-config")
    cargs.append(params.get("key", None))
    cargs.append(params.get("value", None))
    return cargs


class Label2colourOutputs(typing.NamedTuple):
    """
    Output object returned when calling `Label2colourParameters(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    colour_out: OutputPathType
    """the output colour image"""


def label2colour_params(
    nodes_in: InputPathType,
    colour_out: str,
    lut: InputPathType | None = None,
    info: bool = False,
    quiet: bool = False,
    debug: bool = False,
    force: bool = False,
    nthreads: int | None = None,
    config: list[Label2colourConfigParameters] | None = None,
    help_: bool = False,
    version: bool = False,
) -> Label2colourParametersTagged:
    """
    Build parameters.
    
    Args:
        nodes_in: the input node parcellation image.
        colour_out: the output colour image.
        lut: Provide the relevant colour lookup table (if not provided, nodes\
            will be coloured randomly).
        info: display information messages.
        quiet: do not display information messages or progress status;\
            alternatively, this can be achieved by setting the MRTRIX_QUIET\
            environment variable to a non-empty string.
        debug: display debugging messages.
        force: force overwrite of output files (caution: using the same file as\
            input and output might cause unexpected behaviour).
        nthreads: use this number of threads in multi-threaded applications\
            (set to 0 to disable multi-threading).
        config: temporarily set the value of an MRtrix config file entry.
        help_: display this information page and exit.
        version: display version information and exit.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "mrtrix/label2colour",
        "info": info,
        "quiet": quiet,
        "debug": debug,
        "force": force,
        "help": help_,
        "version": version,
        "nodes_in": nodes_in,
        "colour_out": colour_out,
    }
    if lut is not None:
        params["lut"] = lut
    if nthreads is not None:
        params["nthreads"] = nthreads
    if config is not None:
        params["config"] = config
    return params


def label2colour_cargs(
    params: Label2colourParameters,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("label2colour")
    if params.get("lut", None) is not None:
        cargs.extend([
            "-lut",
            execution.input_file(params.get("lut", None))
        ])
    if params.get("info", False):
        cargs.append("-info")
    if params.get("quiet", False):
        cargs.append("-quiet")
    if params.get("debug", False):
        cargs.append("-debug")
    if params.get("force", False):
        cargs.append("-force")
    if params.get("nthreads", None) is not None:
        cargs.extend([
            "-nthreads",
            str(params.get("nthreads", None))
        ])
    if params.get("config", None) is not None:
        cargs.extend([a for c in [label2colour_config_cargs(s, execution) for s in params.get("config", None)] for a in c])
    if params.get("help", False):
        cargs.append("-help")
    if params.get("version", False):
        cargs.append("-version")
    cargs.append(execution.input_file(params.get("nodes_in", None)))
    cargs.append(params.get("colour_out", None))
    return cargs


def label2colour_outputs(
    params: Label2colourParameters,
    execution: Execution,
) -> Label2colourOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = Label2colourOutputs(
        root=execution.output_file("."),
        colour_out=execution.output_file(params.get("colour_out", None)),
    )
    return ret


def label2colour_execute(
    params: Label2colourParameters,
    runner: Runner | None = None,
) -> Label2colourOutputs:
    """
    label2colour
    
    Convert a parcellated image (where values are node indices) into a colour
    image.
    
    Many software packages handle this colouring internally within their viewer
    program; this binary explicitly converts a parcellation image into a colour
    image that should be viewable in any software.
    
    References:
    
    .
    
    Author: MRTrix3 Developers
    
    URL: https://www.mrtrix.org/
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `Label2colourOutputs`).
    """
    runner = runner or get_global_runner()
    execution = runner.start_execution(LABEL2COLOUR_METADATA)
    params = execution.params(params)
    cargs = label2colour_cargs(params, execution)
    ret = label2colour_outputs(params, execution)
    execution.run(cargs)
    return ret


def label2colour(
    nodes_in: InputPathType,
    colour_out: str,
    lut: InputPathType | None = None,
    info: bool = False,
    quiet: bool = False,
    debug: bool = False,
    force: bool = False,
    nthreads: int | None = None,
    config: list[Label2colourConfigParameters] | None = None,
    help_: bool = False,
    version: bool = False,
    runner: Runner | None = None,
) -> Label2colourOutputs:
    """
    label2colour
    
    Convert a parcellated image (where values are node indices) into a colour
    image.
    
    Many software packages handle this colouring internally within their viewer
    program; this binary explicitly converts a parcellation image into a colour
    image that should be viewable in any software.
    
    References:
    
    .
    
    Author: MRTrix3 Developers
    
    URL: https://www.mrtrix.org/
    
    Args:
        nodes_in: the input node parcellation image.
        colour_out: the output colour image.
        lut: Provide the relevant colour lookup table (if not provided, nodes\
            will be coloured randomly).
        info: display information messages.
        quiet: do not display information messages or progress status;\
            alternatively, this can be achieved by setting the MRTRIX_QUIET\
            environment variable to a non-empty string.
        debug: display debugging messages.
        force: force overwrite of output files (caution: using the same file as\
            input and output might cause unexpected behaviour).
        nthreads: use this number of threads in multi-threaded applications\
            (set to 0 to disable multi-threading).
        config: temporarily set the value of an MRtrix config file entry.
        help_: display this information page and exit.
        version: display version information and exit.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `Label2colourOutputs`).
    """
    params = label2colour_params(
        lut=lut,
        info=info,
        quiet=quiet,
        debug=debug,
        force=force,
        nthreads=nthreads,
        config=config,
        help_=help_,
        version=version,
        nodes_in=nodes_in,
        colour_out=colour_out,
    )
    return label2colour_execute(params, runner)


__all__ = [
    "LABEL2COLOUR_METADATA",
    "Label2colourOutputs",
    "label2colour",
    "label2colour_config_params",
    "label2colour_execute",
    "label2colour_params",
]
