# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

TRANSFORMCONVERT_METADATA = Metadata(
    id="d989e00db8a3092cc8404a7694ecd7d449c9f298.boutiques",
    name="transformconvert",
    package="mrtrix",
    container_image_tag="mrtrix3/mrtrix3:3.0.4",
)


TransformconvertConfigParameters = typing.TypedDict('TransformconvertConfigParameters', {
    "@type": typing.NotRequired[typing.Literal["config"]],
    "key": str,
    "value": str,
})
TransformconvertConfigParametersTagged = typing.TypedDict('TransformconvertConfigParametersTagged', {
    "@type": typing.Literal["config"],
    "key": str,
    "value": str,
})


TransformconvertParameters = typing.TypedDict('TransformconvertParameters', {
    "@type": typing.NotRequired[typing.Literal["mrtrix/transformconvert"]],
    "info": bool,
    "quiet": bool,
    "debug": bool,
    "force": bool,
    "nthreads": typing.NotRequired[int | None],
    "config": typing.NotRequired[list[TransformconvertConfigParameters] | None],
    "help": bool,
    "version": bool,
    "input": list[str],
    "operation": str,
    "output": str,
})
TransformconvertParametersTagged = typing.TypedDict('TransformconvertParametersTagged', {
    "@type": typing.Literal["mrtrix/transformconvert"],
    "info": bool,
    "quiet": bool,
    "debug": bool,
    "force": bool,
    "nthreads": typing.NotRequired[int | None],
    "config": typing.NotRequired[list[TransformconvertConfigParameters] | None],
    "help": bool,
    "version": bool,
    "input": list[str],
    "operation": str,
    "output": str,
})


def transformconvert_config_params(
    key: str,
    value: str,
) -> TransformconvertConfigParametersTagged:
    """
    Build parameters.
    
    Args:
        key: temporarily set the value of an MRtrix config file entry.
        value: temporarily set the value of an MRtrix config file entry.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "config",
        "key": key,
        "value": value,
    }
    return params


def transformconvert_config_cargs(
    params: TransformconvertConfigParameters,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("-config")
    cargs.append(params.get("key", None))
    cargs.append(params.get("value", None))
    return cargs


class TransformconvertOutputs(typing.NamedTuple):
    """
    Output object returned when calling `TransformconvertParameters(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    output: OutputPathType
    """the output transformation matrix."""


def transformconvert_params(
    input_: list[str],
    operation: str,
    output: str,
    info: bool = False,
    quiet: bool = False,
    debug: bool = False,
    force: bool = False,
    nthreads: int | None = None,
    config: list[TransformconvertConfigParameters] | None = None,
    help_: bool = False,
    version: bool = False,
) -> TransformconvertParametersTagged:
    """
    Build parameters.
    
    Args:
        input_: the input(s) for the specified operation.
        operation: the operation to perform, one of:\
            flirt_import, itk_import.
        output: the output transformation matrix.
        info: display information messages.
        quiet: do not display information messages or progress status;\
            alternatively, this can be achieved by setting the MRTRIX_QUIET\
            environment variable to a non-empty string.
        debug: display debugging messages.
        force: force overwrite of output files (caution: using the same file as\
            input and output might cause unexpected behaviour).
        nthreads: use this number of threads in multi-threaded applications\
            (set to 0 to disable multi-threading).
        config: temporarily set the value of an MRtrix config file entry.
        help_: display this information page and exit.
        version: display version information and exit.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "mrtrix/transformconvert",
        "info": info,
        "quiet": quiet,
        "debug": debug,
        "force": force,
        "help": help_,
        "version": version,
        "input": input_,
        "operation": operation,
        "output": output,
    }
    if nthreads is not None:
        params["nthreads"] = nthreads
    if config is not None:
        params["config"] = config
    return params


def transformconvert_cargs(
    params: TransformconvertParameters,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("transformconvert")
    if params.get("info", False):
        cargs.append("-info")
    if params.get("quiet", False):
        cargs.append("-quiet")
    if params.get("debug", False):
        cargs.append("-debug")
    if params.get("force", False):
        cargs.append("-force")
    if params.get("nthreads", None) is not None:
        cargs.extend([
            "-nthreads",
            str(params.get("nthreads", None))
        ])
    if params.get("config", None) is not None:
        cargs.extend([a for c in [transformconvert_config_cargs(s, execution) for s in params.get("config", None)] for a in c])
    if params.get("help", False):
        cargs.append("-help")
    if params.get("version", False):
        cargs.append("-version")
    cargs.extend(params.get("input", None))
    cargs.append(params.get("operation", None))
    cargs.append(params.get("output", None))
    return cargs


def transformconvert_outputs(
    params: TransformconvertParameters,
    execution: Execution,
) -> TransformconvertOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = TransformconvertOutputs(
        root=execution.output_file("."),
        output=execution.output_file(params.get("output", None)),
    )
    return ret


def transformconvert_execute(
    params: TransformconvertParameters,
    runner: Runner | None = None,
) -> TransformconvertOutputs:
    """
    transformconvert
    
    Convert linear transformation matrices.
    
    This command allows to convert transformation matrices provided by other
    registration softwares to a format usable in MRtrix3. Example usages are
    provided below.
    
    References:
    
    .
    
    Author: MRTrix3 Developers
    
    URL: https://www.mrtrix.org/
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `TransformconvertOutputs`).
    """
    runner = runner or get_global_runner()
    execution = runner.start_execution(TRANSFORMCONVERT_METADATA)
    params = execution.params(params)
    cargs = transformconvert_cargs(params, execution)
    ret = transformconvert_outputs(params, execution)
    execution.run(cargs)
    return ret


def transformconvert(
    input_: list[str],
    operation: str,
    output: str,
    info: bool = False,
    quiet: bool = False,
    debug: bool = False,
    force: bool = False,
    nthreads: int | None = None,
    config: list[TransformconvertConfigParameters] | None = None,
    help_: bool = False,
    version: bool = False,
    runner: Runner | None = None,
) -> TransformconvertOutputs:
    """
    transformconvert
    
    Convert linear transformation matrices.
    
    This command allows to convert transformation matrices provided by other
    registration softwares to a format usable in MRtrix3. Example usages are
    provided below.
    
    References:
    
    .
    
    Author: MRTrix3 Developers
    
    URL: https://www.mrtrix.org/
    
    Args:
        input_: the input(s) for the specified operation.
        operation: the operation to perform, one of:\
            flirt_import, itk_import.
        output: the output transformation matrix.
        info: display information messages.
        quiet: do not display information messages or progress status;\
            alternatively, this can be achieved by setting the MRTRIX_QUIET\
            environment variable to a non-empty string.
        debug: display debugging messages.
        force: force overwrite of output files (caution: using the same file as\
            input and output might cause unexpected behaviour).
        nthreads: use this number of threads in multi-threaded applications\
            (set to 0 to disable multi-threading).
        config: temporarily set the value of an MRtrix config file entry.
        help_: display this information page and exit.
        version: display version information and exit.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `TransformconvertOutputs`).
    """
    params = transformconvert_params(
        info=info,
        quiet=quiet,
        debug=debug,
        force=force,
        nthreads=nthreads,
        config=config,
        help_=help_,
        version=version,
        input_=input_,
        operation=operation,
        output=output,
    )
    return transformconvert_execute(params, runner)


__all__ = [
    "TRANSFORMCONVERT_METADATA",
    "TransformconvertOutputs",
    "transformconvert",
    "transformconvert_config_params",
    "transformconvert_execute",
    "transformconvert_params",
]
