# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

MRI_EXTRACT_FCD_FEATURES_METADATA = Metadata(
    id="822940a66948e150cdf82461b3ef67a0620a6fc0.boutiques",
    name="mri_extract_fcd_features",
    package="freesurfer",
    container_image_tag="freesurfer/freesurfer:7.4.1",
)


MriExtractFcdFeaturesParameters = typing.TypedDict('MriExtractFcdFeaturesParameters', {
    "@type": typing.NotRequired[typing.Literal["freesurfer/mri_extract_fcd_features"]],
    "subject": str,
    "hemi": str,
    "output_file": InputPathType,
    "subjects_dir": typing.NotRequired[str | None],
})
MriExtractFcdFeaturesParametersTagged = typing.TypedDict('MriExtractFcdFeaturesParametersTagged', {
    "@type": typing.Literal["freesurfer/mri_extract_fcd_features"],
    "subject": str,
    "hemi": str,
    "output_file": InputPathType,
    "subjects_dir": typing.NotRequired[str | None],
})


class MriExtractFcdFeaturesOutputs(typing.NamedTuple):
    """
    Output object returned when calling `MriExtractFcdFeaturesParameters(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""


def mri_extract_fcd_features_params(
    subject: str,
    hemi: str,
    output_file: InputPathType,
    subjects_dir: str | None = None,
) -> MriExtractFcdFeaturesParametersTagged:
    """
    Build parameters.
    
    Args:
        subject: The subject identifier.
        hemi: The hemisphere (e.g., lh or rh).
        output_file: Output file path.
        subjects_dir: Specify SUBJECTS_DIR on the command line instead of in\
            the environment.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "freesurfer/mri_extract_fcd_features",
        "subject": subject,
        "hemi": hemi,
        "output_file": output_file,
    }
    if subjects_dir is not None:
        params["subjects_dir"] = subjects_dir
    return params


def mri_extract_fcd_features_cargs(
    params: MriExtractFcdFeaturesParameters,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("mri_extract_fcd_features")
    cargs.append(params.get("subject", None))
    cargs.append(params.get("hemi", None))
    cargs.append(execution.input_file(params.get("output_file", None)))
    if params.get("subjects_dir", None) is not None:
        cargs.extend([
            "sdir",
            params.get("subjects_dir", None)
        ])
    return cargs


def mri_extract_fcd_features_outputs(
    params: MriExtractFcdFeaturesParameters,
    execution: Execution,
) -> MriExtractFcdFeaturesOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = MriExtractFcdFeaturesOutputs(
        root=execution.output_file("."),
    )
    return ret


def mri_extract_fcd_features_execute(
    params: MriExtractFcdFeaturesParameters,
    runner: Runner | None = None,
) -> MriExtractFcdFeaturesOutputs:
    """
    mri_extract_fcd_features
    
    A tool for extracting focal cortical dysplasia features.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MriExtractFcdFeaturesOutputs`).
    """
    runner = runner or get_global_runner()
    execution = runner.start_execution(MRI_EXTRACT_FCD_FEATURES_METADATA)
    params = execution.params(params)
    cargs = mri_extract_fcd_features_cargs(params, execution)
    ret = mri_extract_fcd_features_outputs(params, execution)
    execution.run(cargs)
    return ret


def mri_extract_fcd_features(
    subject: str,
    hemi: str,
    output_file: InputPathType,
    subjects_dir: str | None = None,
    runner: Runner | None = None,
) -> MriExtractFcdFeaturesOutputs:
    """
    mri_extract_fcd_features
    
    A tool for extracting focal cortical dysplasia features.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        subject: The subject identifier.
        hemi: The hemisphere (e.g., lh or rh).
        output_file: Output file path.
        subjects_dir: Specify SUBJECTS_DIR on the command line instead of in\
            the environment.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MriExtractFcdFeaturesOutputs`).
    """
    params = mri_extract_fcd_features_params(
        subject=subject,
        hemi=hemi,
        output_file=output_file,
        subjects_dir=subjects_dir,
    )
    return mri_extract_fcd_features_execute(params, runner)


__all__ = [
    "MRI_EXTRACT_FCD_FEATURES_METADATA",
    "MriExtractFcdFeaturesOutputs",
    "mri_extract_fcd_features",
    "mri_extract_fcd_features_execute",
    "mri_extract_fcd_features_params",
]
