# This file was auto generated by Styx.
# Do not edit this file directly.

import typing
import pathlib
from styxdefs import *

MRIS_GRADIENT_METADATA = Metadata(
    id="f6760899fb661a954861cf6ca458010aedcf71b9.boutiques",
    name="mris_gradient",
    package="freesurfer",
    container_image_tag="freesurfer/freesurfer:7.4.1",
)


MrisGradientParameters = typing.TypedDict('MrisGradientParameters', {
    "@type": typing.NotRequired[typing.Literal["freesurfer/mris_gradient"]],
    "input_surface": InputPathType,
    "input_vector_field": InputPathType,
    "output_gradient_file": str,
})
MrisGradientParametersTagged = typing.TypedDict('MrisGradientParametersTagged', {
    "@type": typing.Literal["freesurfer/mris_gradient"],
    "input_surface": InputPathType,
    "input_vector_field": InputPathType,
    "output_gradient_file": str,
})


class MrisGradientOutputs(typing.NamedTuple):
    """
    Output object returned when calling `MrisGradientParameters(...)`.
    """
    root: OutputPathType
    """Output root folder. This is the root folder for all outputs."""
    output_gradient: OutputPathType
    """The resulting gradient measurement written into a .mgz file."""


def mris_gradient_params(
    input_surface: InputPathType,
    input_vector_field: InputPathType,
    output_gradient_file: str,
) -> MrisGradientParametersTagged:
    """
    Build parameters.
    
    Args:
        input_surface: Path to the input surface file.
        input_vector_field: Path to the input vector field file.
        output_gradient_file: Path to the output gradient file ending with\
            .mgz.
    Returns:
        Parameter dictionary
    """
    params = {
        "@type": "freesurfer/mris_gradient",
        "input_surface": input_surface,
        "input_vector_field": input_vector_field,
        "output_gradient_file": output_gradient_file,
    }
    return params


def mris_gradient_cargs(
    params: MrisGradientParameters,
    execution: Execution,
) -> list[str]:
    """
    Build command-line arguments from parameters.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Command-line arguments.
    """
    cargs = []
    cargs.append("mris_gradient")
    cargs.append(execution.input_file(params.get("input_surface", None)))
    cargs.append(execution.input_file(params.get("input_vector_field", None)))
    cargs.append(params.get("output_gradient_file", None))
    return cargs


def mris_gradient_outputs(
    params: MrisGradientParameters,
    execution: Execution,
) -> MrisGradientOutputs:
    """
    Build outputs object containing output file paths and possibly stdout/stderr.
    
    Args:
        params: The parameters.
        execution: The execution object for resolving input paths.
    Returns:
        Outputs object.
    """
    ret = MrisGradientOutputs(
        root=execution.output_file("."),
        output_gradient=execution.output_file(params.get("output_gradient_file", None)),
    )
    return ret


def mris_gradient_execute(
    params: MrisGradientParameters,
    runner: Runner | None = None,
) -> MrisGradientOutputs:
    """
    mris_gradient
    
    This program computes the gradient of an intensity profile of the cortical
    ribbon and writes the resulting measurement into a .mgz file.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        params: The parameters.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MrisGradientOutputs`).
    """
    runner = runner or get_global_runner()
    execution = runner.start_execution(MRIS_GRADIENT_METADATA)
    params = execution.params(params)
    cargs = mris_gradient_cargs(params, execution)
    ret = mris_gradient_outputs(params, execution)
    execution.run(cargs)
    return ret


def mris_gradient(
    input_surface: InputPathType,
    input_vector_field: InputPathType,
    output_gradient_file: str,
    runner: Runner | None = None,
) -> MrisGradientOutputs:
    """
    mris_gradient
    
    This program computes the gradient of an intensity profile of the cortical
    ribbon and writes the resulting measurement into a .mgz file.
    
    Author: FreeSurfer Developers
    
    URL: https://github.com/freesurfer/freesurfer
    
    Args:
        input_surface: Path to the input surface file.
        input_vector_field: Path to the input vector field file.
        output_gradient_file: Path to the output gradient file ending with\
            .mgz.
        runner: Command runner.
    Returns:
        NamedTuple of outputs (described in `MrisGradientOutputs`).
    """
    params = mris_gradient_params(
        input_surface=input_surface,
        input_vector_field=input_vector_field,
        output_gradient_file=output_gradient_file,
    )
    return mris_gradient_execute(params, runner)


__all__ = [
    "MRIS_GRADIENT_METADATA",
    "MrisGradientOutputs",
    "mris_gradient",
    "mris_gradient_execute",
    "mris_gradient_params",
]
